################ English language ##################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 2

[it]
languageName = "it"
languageCode = "it-it"
contentDir = "content/italian"
weight = 1
